# keywords
ğŸ“‹: class
ğŸ“¦: module
ğŸ”œ: def
ğŸ”š: end
ğŸš£: self
âœ‹: yield
â›”ï¸: private
ğŸ‘‰: "->"
ğŸ”¨: do
â¿: loop
ğŸ¡: while

# symbols
ğŸ’¬: "\""
â–ªï¸: "."
â†ªï¸: "("
â†©ï¸: ")"
â°: ","

# conveniences
ğŸ‘€: puts
ğŸ£: new
ğŸ’¥: raise
â•: +
ğŸš°: tap
ğŸ“: call
âš ï¸: warn
