# keywords
ğŸ“‹: class
ğŸ“¦: module
ğŸ”œ: def
ğŸ”š: end
ğŸš£: self
âœ‹: yield
ğŸ”“: public
ğŸ”’: protected
â›”ï¸: private
ğŸ‘‰: "->"
ğŸ”¨: do
â¿: loop
ğŸ¡: while

# symbols
ğŸ’¬: "\""
â–ªï¸: "."
â†ªï¸: "("
â†©ï¸: ")"
â—€ï¸: "["
â–¶ï¸: "]"
âª: "{"
â©: "}"
ğŸ‚: "|"
â°: ","
ğŸ’­: "#"

# literals
1ï¸âƒ£: "1"
2ï¸âƒ£: "2"
3ï¸âƒ£: "3"
4ï¸âƒ£: "4"
5ï¸âƒ£: "5"
6ï¸âƒ£: "6"
7ï¸âƒ£: "7"
8ï¸âƒ£: "8"
9ï¸âƒ£: "9"
0ï¸âƒ£: "0"


# conveniences
ğŸ‘€: puts
ğŸ£: new
ğŸ’¥: raise
ğŸš°: tap
ğŸ“: call
âš ï¸: warn
ğŸ“: map
â•: "+"
â–: "-"
â—: "/"
âœ–ï¸: "*"